// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: OLED_I2C

#ifndef _OLED_I2C_UI_H
#define _OLED_I2C_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_bluetooth_ic_png);    // assets/bluetooth_ic.png
LV_IMG_DECLARE(ui_img_brightness_ic_png);    // assets/brightness_ic.png
LV_IMG_DECLARE(ui_img_airplane_ic_png);    // assets/airplane_ic.png
LV_IMG_DECLARE(ui_img_img0_png);    // assets/img0.png
LV_IMG_DECLARE(ui_img_img1_png);    // assets/img1.png
LV_IMG_DECLARE(ui_img_img2_png);    // assets/img2.png
LV_IMG_DECLARE(ui_img_img3_png);    // assets/img3.png
LV_IMG_DECLARE(ui_img_img4_png);    // assets/img4.png
LV_IMG_DECLARE(ui_img_img5_png);    // assets/img5.png
LV_IMG_DECLARE(ui_img_img6_png);    // assets/img6.png
LV_IMG_DECLARE(ui_img_img7_png);    // assets/img7.png
LV_IMG_DECLARE(ui_img_img8_png);    // assets/img8.png
LV_IMG_DECLARE(ui_img_img9_png);    // assets/img9.png



LV_FONT_DECLARE(ui_font_Font1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
